portfolio clickable to stock viewer/portfolio backend tests/few front…
CSE115aStock/StockCSE115A pull request #36
Opened 2022-03-05 22:05 UTC by mihika-marathe

…end tests

2022-03-05 22:19 UTC, ojas1542 requested changes
None of the portfolio tests pass for me...think you need to add the verify_jwt_in_request call to all the portfolio endpoints

2022-03-05 22:50 UTC, mihika-marathe commented
Oh sorry I made that change to portfolio.py but forgot to add it when committing, I'll add it

2022-03-06 05:24 UTC, ojas1542 approved these changes

2022-03-08 20:45 UTC, ojas1542 approved these changes

2022-03-08 20:52 UTC, merged